FORMAT: 1A
HOST: http://polls.apiblueprint.org/

# iot-heating-switch

IOT Heating switch. Switching heating on multiple floors.

## House info [/house/{house_id}]

Change, get house heating switch data

### List of floor temperatures [GET]

Returns with a list of statuses of all floors in a given house.

`num-floors` is nonnegative integer indicating number of floors
in the house.
    
`status` is either `"on"` or `"off"`

Floor index of the `i` 'th entry in "floors" list is `i` itself.

+ Response 200 (application/json)

        {
            "num-floors": 3,
            "floors": [
                {
                    "status": "on"
                },
                {
                    "status": "off"
                },
                {
                    "status": "off"
                }
            ]
        }


## Floor switch [/house/{house_id}/floor/{floor_id}]

### Get floor temperature [GET]

Returns a status of a switch on a given house and a floor.
On success returns with status code 200 with body containing
switch status.

`status` is `"on"` or `"off"`

+ Response 200 (application/json)

        {
            "status": "on"
        }

+ Response 404 (application/json)


### Switch Floor [POST]

Changes switch status on a given house/floor.
On success returns with code 200, if house or floor number
is not valid 404 is returned. If other problem occurs code will
be different.

`status` must be `"on"` or `"off"`, `period` is a nonnegative integer
representing number of seconds to keep switch status. After that
if no other switch request is received switch will move to
'safe state'.NI 

+ Request (application/json)

        {
            "status": "on",
            "period": 600
        }

+ Response 200 (application/json)

+ Response 404 (application/json)